### ISSUE TITLE
Issue on generating README.md

### ISSUE THREAD

**Issue by chevybowtie** [tom-doerr/codex-readme#2]
Found your project on Reddit so I thought I'd give it a try. 

I tried this on my project, and it started generating (what I assume is) the README to my screen, but it ended prematurely with the following: 
```
Traceback (most recent call last):
  File "../codex-readme/codex_readme.py", line 196, in <module>
    generate_until_accepted(input_prompt, args.tokens)
  File "../codex-readme/codex_readme.py", line 169, in generate_until_accepted
    generated_readme = clear_screen_and_display_generated_readme(response)
  File "../codex-readme/codex_readme.py", line 116, in clear_screen_and_display_generated_readme
    next_response = next(response)
StopIteration
```

**Comment by stoffl6781** [comment]
if i add your bugfix, than i get an blank readme.md file.

**Comment by janrosendahl** [comment]
I added a try/catch to the next(response) which 
dropped out otherwise after the last call

```python
def clear_screen_and_display_generated_readme(response):
    # Clear screen.
    os.system('cls' if os.name == 'nt' else 'clear')
    generated_readme = ''
    print(README_START)
    generated_readme = README_START
    while True:
        try:
            next_response = next(response)
        except StopIteration:
            print("No more items in the response")
            break
        except Exception as e:
            print(f"An error occurred: {e}")
            break
        completion = next_response['choices'][0]['text']
        # print("completion:", completion)
        # print(next(response))
        generated_readme = generated_readme + completion
        if next_response['choices'][0]['finish_reason'] != None: break
    return generated_readme
```

**Comment by tom-doerr** [comment]
Just merged this PR: https://github.com/tom-doerr/codex-readme/pull/3
Maybe it works for you now
