### ISSUE TITLE
StopIteration Error

### ISSUE THREAD

**Issue by b1tw0rker** [tom-doerr/codex-readme#4]
Hi Tom,
I just implemented the API Key in ~/.config/openaiapirc
with the folowing content:

```
[openai]
organization_id=org-MY_ORGANIZATION_KEY
secret_key=sk-MY_API_KEY

```

The module openai is installed fine.
I am running Python3 on Windows.

After starting the program with:

```
python ./codex-readme.py
```
I get these output error:

```
...
You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.


Traceback (most recent call last):
  File "C:\dev\codex-readme\codex_readme.py", line 196, in <module>
    generate_until_accepted(input_prompt, args.tokens)
  File "C:\dev\codex-readme\codex_readme.py", line 169, in generate_until_accepted
    generated_readme = clear_screen_and_display_generated_readme(response)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\dev\codex-readme\codex_readme.py", line 116, in clear_screen_and_display_generated_readme
    next_response = next(response)
                    ^^^^^^^^^^^^^^
StopIteration
```

Any help would be appreciated.

**Comment by b1tw0rker** [comment]
On linux system (Rocky8 , Python 3.6) I get kind of an equal error:
But secret key and organizaion id is present on the wanted place.

```
Once you have your organization ID and secret key, create a file called
~/.config/openaiapirc with the following contents:

```
[openai]
organization_id=YOUR_ORG_ID
secret_key=YOUR_SECRET_KEY
```

Traceback (most recent call last):
  File "./codex_readme.py", line 196, in <module>
    generate_until_accepted(input_prompt, args.tokens)
  File "./codex_readme.py", line 169, in generate_until_accepted
    generated_readme = clear_screen_and_display_generated_readme(response)
  File "./codex_readme.py", line 116, in clear_screen_and_display_generated_readme
    next_response = next(response)
StopIteration
```
